spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/usuarios
    username: postgres
    password: GrestC@rlosPost978
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
